export const REGISTRATION_START = 'REGISTRATION_START'
export const REGISTRATION_SUCCES = 'REGISTRATION_SUCCES'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCES = 'LOGIN_SUCCES'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'